export const NOTION_COLOR_MAP: Record<string, string> = {
  gray: 'text-gray-500',
  brown: 'text-amber-700',
  orange: 'text-orange-500',
  yellow: 'text-yellow-500',
  green: 'text-green-600',
  blue: 'text-blue-600',
  purple: 'text-purple-600',
  pink: 'text-pink-600',
  red: 'text-red-600',
  gray_background: 'bg-gray-100 px-1 rounded',
  brown_background: 'bg-amber-100 px-1 rounded',
  orange_background: 'bg-orange-100 px-1 rounded',
  yellow_background: 'bg-yellow-100 px-1 rounded',
  green_background: 'bg-green-100 px-1 rounded',
  blue_background: 'bg-blue-100 px-1 rounded',
  purple_background: 'bg-purple-100 px-1 rounded',
  pink_background: 'bg-pink-100 px-1 rounded',
  red_background: 'bg-red-100 px-1 rounded',
}
